### ISSUE TITLE
when your code are released?

### ISSUE THREAD

**Issue by hujunchao** [TonyLianLong/LLM-groundedDiffusion#1]
Thanks for your great job. And when your code will be released?

**Comment by TonyLianLong** [comment]
We already have a demo for stage 1 (you can click "Files" to see the code): https://huggingface.co/spaces/longlian/llm-grounded-diffusion

For stage 2, we have a locally running demo, and we are applying for community grant. If approved, we will add stage 2 to the demo soon.

**Comment by TonyLianLong** [comment]
We have released the stage 2 in a gradio app. See README for this repo.

**Comment by hujunchao** [comment]
very good!

**Comment by TonyLianLong** [comment]
May I close this issue?
