### ISSUE TITLE
How to Visualize the masked latents or the attention maps

### ISSUE THREAD

**Issue by ayanban011** [TonyLianLong/LLM-groundedDiffusion#14]
Hi, I am working with LLM grounded diffusion and facing some issues. I cannot visualize the mask_latents or attention maps even if I enable the following code in lmd_plus.py or lmd.py
````
if visualize:
        vis.visualize(mask_selected, "Mask (selected) after resize")
        # This is only for visualizations
        masked_latents = latents_all * mask_selected_tensor
        vis.visualize_masked_latents(
            latents_all, masked_latents, timestep_T=False, timestep_0=True
````
Can you please help me with that?
Thanks

**Comment by TonyLianLong** [comment]
What did you observe? Did it give you an error? It should pop up a `matplotlib` window if you're on a desktop. If you're on the server, you probably want to do X window forwarding with ssh.

**Comment by ayanban011** [comment]
I am doing it in the Visual Studio code. No window has been popped up. Even I tried to save the plot with plt.savefig but nothing happened. It seems that the masek_selected_tensor is always None.

**Comment by ayanban011** [comment]
Hi, The issues has been resolved, so I am closing it. Thanks for your help.
