### ISSUE TITLE
"TypeError: Linear.forward() takes 2 positional arguments but 3 were given" when trying to replicate the pipeline with diffusers

### ISSUE THREAD

**Issue by cwirzenm** [TonyLianLong/LLM-groundedDiffusion#17]
Here's my code. I pretty much copied it across from your README.
```
from diffusers import DiffusionPipeline
import torch

print("Torch version:", torch.__version__)
print("Is CUDA enabled?", torch.cuda.is_available())

pipe = DiffusionPipeline.from_pretrained(
        "longlian/lmd_plus",
        custom_pipeline="llm_grounded_diffusion",
        custom_revision="main",
        torch_dtype=torch.float16,
        variant="fp16")
pipe.to("cuda")

prompt = "a waterfall and a modern high speed train in a beautiful forest with fall foliage."
response = """
[('a waterfall', [100, 50, 200, 450]), ('a beautiful deer', [350, 250, 150, 200])] Background prompt: A dense forest surrounded by mountains Negative prompt:
"""

phrases, boxes, bg_prompt, neg_prompt = pipe.parse_llm_response(response)

image = pipe(
    prompt=prompt,
    negative_prompt=neg_prompt,
    phrases=phrases,
    boxes=boxes,
    gligen_scheduled_sampling_beta=0.4,
    output_type="pil",
    num_inference_steps=50,
    lmd_guidance_kwargs={}
).images

image[0].show()
```

Here's the stacktrace:
> Loading pipeline components...:  57%|█████▋    | 4/7 [00:00<00:00,  5.76it/s]`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
> `text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
> `text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
> Loading pipeline components...: 100%|██████████| 7/7 [00:01<00:00,  6.19it/s]
>   0%|          | 0/50 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "...\.cache\huggingface\modules\diffusers_modules\git\llm_grounded_diffusion.py", line 1019, in __call__
>     latents, loss_attn = self.latent_lmd_guidance(
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "...\.cache\huggingface\modules\diffusers_modules\git\llm_grounded_diffusion.py", line 1129, in latent_lmd_guidance
>     unet(
>   File ...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\diffusers\models\unets\unet_2d_condition.py", line 1216, in forward
>     sample, res_samples = downsample_block(
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 1279, in forward
>     hidden_states = attn(
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\diffusers\models\transformers\transformer_2d.py", line 397, in forward
>     hidden_states = block(
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\diffusers\models\attention.py", line 366, in forward
>     attn_output = self.attn2(
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\diffusers\models\attention_processor.py", line 522, in forward
>     return self.processor(
>   File "...\.cache\huggingface\modules\diffusers_modules\git\llm_grounded_diffusion.py", line 198, in __call__
>     query = attn.to_q(hidden_states, *args)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "...\anaconda3\envs\conda310diss\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
> TypeError: Linear.forward() takes 2 positional arguments but 3 were given

Torch: 2.1.2+cu118
accelerate: 0.21.0 
transformers: 4.31.0 
diffusers: 0.27.2

I've been trying to troubleshoot but it seems like the error is coming from inside the package. I will try to fork your repo and work with it directly, but I thought it will be useful to flag this here.

**Comment by TonyLianLong** [comment]
Thanks for reporting this. Can you try installing peft and upgrading transformers? `transformers` 4.13.0 is too old to work with `diffusers` 0.27.2, so it's not detected.

```
pip install accelerate==0.21.0 transformers==4.39.3 diffusers==0.27.2 peft==0.10.0
```

I just tested this on [colab](https://colab.research.google.com/drive/1SXzMSeAB-LJYISb2yrUOdypLz4OYWUKj) and it works.

**Comment by cwirzenm** [comment]
Just checked and it works. Package compatibility is tricky to get right sometimes. Thanks a lot!
