### ISSUE TITLE
Does it only generate bboxes that are not overlapped? 

### ISSUE THREAD

**Issue by Colezwhy** [TonyLianLong/LLM-groundedDiffusion#18]
First, thank you for your great work!
And I am very interested whether this method could generate bbox instances that have overlaps between each other?
For example, a dog wearing a sweater, what will it produce？

**Comment by TonyLianLong** [comment]
Thanks for the great question. The example you provided is similar to the example I presented in #2 . Our method can generate a man riding a horse, which requires handling bounding box overlaps.

**Comment by Colezwhy** [comment]
> Thanks for the great question. The example you provided is similar to the example I presented in #2 . Our method can generate a man riding a horse, which requires handling bounding box overlaps.

Thank you for your patience, nice work!
