### ISSUE TITLE
[FR] Finetuning Model using Dreambooth

### ISSUE THREAD

**Issue by mauricio-repetto** [TonyLianLong/LLM-groundedDiffusion#6]
Hi, will it be possible to finetune this model using dreambooth technique?

**Comment by TonyLianLong** [comment]
I think it's possible. This codebase uses diffusers so it should also be compatible.

You can fine-tune with dreambooth for personalization and then perform generation using our method.

**Comment by mauricio-repetto** [comment]
Cool! I'll try then. Thanks!
