### ISSUE TITLE
ImportError: cannot import name 'Annotated' from 'pydantic.typing'

### ISSUE THREAD

**Issue by XiaominLi1997** [TonyLianLong/LLM-groundedDiffusion#8]
Hello, I have no idea about this error. Could you please have a look? Thx
![image](https://github.com/TonyLianLong/LLM-groundedDiffusion/assets/25433111/ad2fdd95-b328-4a32-b4c0-4a04cd5c2114)

**Comment by TonyLianLong** [comment]
Seems like somehow you cannot import the inflect package.

This might help: https://stackoverflow.com/questions/76593169/importerror-cannot-import-name-annotated-from-pydantic-typing-when-using-in

**Comment by XiaominLi1997** [comment]
Hi,
I am using pydantic-2.3.0, which version do you use?
Thx

**Comment by XiaominLi1997** [comment]
I change the version to 1.10.10. It works now. Thx again.

**Comment by TonyLianLong** [comment]
Glad to see it works. I use `pydantic==1.10.7`. I will add this to the requirements.
